### ISSUE TITLE
consider approach of splitting schema definition and form definition

### ISSUE THREAD

**Issue by ssured** [aptible/ember-json-schema-document#43]
I got some inspiration from https://github.com/Textalk/angular-schema-form

To me it seems a more sensible solution to split the strict schema from the less strict form. This allows for having multiple forms on the same data. For me that is useful, as my users have different roles acting on the shared data.

**Comment by sandersonet** [comment]
Thanks for this @ssured -- I agree entirely.  We'll push for this in the coming weeks.
